### ISSUE TITLE
after "gulp serve-dev" browser-sync error.

### ISSUE THREAD

**Issue by jkRaccoon** [johnpapa/generator-hottowel#171] opened 2016-04-12 09:55 UTC
![5](https://cloud.githubusercontent.com/assets/13463360/14456367/87e722c4-00df-11e6-9bec-be2912f87da6.PNG)
![6](https://cloud.githubusercontent.com/assets/13463360/14456376/8d1e0730-00df-11e6-9c36-c7bb01f59c93.PNG)

after browser open. it shows nothing and endless loading.

8001 port is clearly works well, and 3001 port(UI) is also works fine.

I don`t know why.

**Comment by norman92** [comment] 2016-04-12 10:13
I am experiencing this error too.

**Comment by EtienneAribaud** [comment] 2016-04-12 13:17
Hi,
I am having the same issue...
Any solution?

**Comment by jkRaccoon** [comment] 2016-04-12 17:50
I found answer myself. 
proxy is problem. 

when I change http://127.0.0.1:3000 (or external ip) instead of http://localhost:3000. it works. 

simple. :)

**Comment by bytelovers** [comment] 2016-04-12 18:36
Hi,

I changed the URL to IP but It not worked for me.... :(

Any other solution?

**Comment by johnpapa** [comment] 2016-04-12 22:17
Do we have any information on the scenario? I'd love to help debug this.

**Comment by brandonsherette** [comment] 2016-04-12 22:45
I'm having a similar issue, and I noticed that when I typed in the port to the express's 8001 (localhost:8001), everything was running ok. Port 3000, the one browser-sync is using, would just have it load forever and saying "Cannot read property 'offsetWidth' of null" in the browser console, much like the first post's image. 

Also, I noticed in my case (port 3000 version), when I removed the ui-view tag from the shell.html it would run correctly. So I'm thinking it has to do with browser-sync with port 3000 and dealing with the routing to the ui-view, at least in my case.

Also, when I use serve-build, everything runs correctly as well, so to narrow it down, it's dealing with gulp serve-dev and browser-sync port 3000 and dealing with the ui-view. As a side-note, I just tried again with a fresh install of hottowel on one of my other machines, and I'm running into the same issue.

**Comment by johnpapa** [comment] 2016-04-13 00:19
It would be very helpful to know:
- OS
- node version
- npm version
- hottowel version

and any other environment settings too

**Comment by johnpapa** [comment] 2016-04-13 00:59
Seems to be an open issue in browser-sync https://github.com/BrowserSync/browser-sync/issues/1062

**Comment by brandonsherette** [comment] 2016-04-13 01:42
Ya looks like that was it. From the looks of it, when I was trying out jkRaccoon's solution earlier, my browser was automatically changing it back to the localhost version.

Interesting to note that after using 127.0.0.1:3000 and closing the server connection and re-issuing out the gulp serve-dev command, the localhost:3000 works for awhile until I restart my computer, then I have to use 127.0.0.1 for the first time again and seems to run fine afterwards.

Thanks for the help, and the link about the issue with browser-sync.

**Comment by johnpapa** [comment] 2016-04-13 02:05
For now use 127.0.0.1

There are serveral open issues on browser sync related to this

https://github.com/BrowserSync/browser-sync/issues/1046

https://github.com/BrowserSync/browser-sync/issues/1049

https://github.com/BrowserSync/browser-sync/issues/936

**Comment by johnpapa** [comment] 2016-04-13 02:23
I reverted to bs 2.11 in this commit and it seems to work now.

it appears to be an issue with browser-sync 2.12.

i just published 0.4.1 to npm. See if that helps

**Comment by brandonsherette** [comment] 2016-04-13 05:11
Update 0.4.1 seems to be working out nicely. I haven't had any issues so far with localhost:3000. 

I executed gulp serve-dev about 20 times, even with restarting computer and installing hottowel in 2 separate installations, and no issues.

**Comment by shakyShane** [comment] 2016-04-13 06:00
I will be providing a fix to the Browsersync module asap :)

**Comment by bytelovers** [comment] 2016-04-13 06:12
hi @johnpapa 

With that fix you solved the problem, thx so much! :+1:

**Comment by shakyShane** [comment] 2016-04-13 07:35
Fixed via a patch release `browser-sync@2.12.2`

Apologies for any disruption caused :)

**Comment by norman92** [comment] 2016-04-13 08:05
I have updated to browser-sync@2.12.2 and now the issue is resolved for me

**Comment by johnpapa** [comment] 2016-04-13 16:33
Thanks @shakyShane !!!

Really appreciate the quick help. We use browser-sync in a lot of places :)

**Comment by shakyShane** [comment] 2016-04-13 16:48
@johnpapa any time, glad to help :)

**Comment by EtienneAribaud** [comment] 2016-04-13 17:11
Problem solved. Thank you for your amazing work!!!

**Comment by Codermar** [comment] 2016-04-17 00:47
I was interested in this thread because I've been having trouble for a while but my use case is slightly different. When using VPN, it takes a long time to load (a minute or maybe longer). I know it's related to VPN or some proxy issue because I disconnect VPN and then it fires fine a few seconds later. Also, when running my app with maven and the Java backend, browser sync never fires (perhaps a related issue?) I'll try to provide more info.

**Closed** 2016-04-23 00:33 UTC
Labels: bug, help wanted
